services:
    app:
        build:
            context: ./finance
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - ./finance:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    db:
        image: mysql:8.0
        container_name: mysql_db
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"

volumes:
    db_data:
