version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: finance
        volumes:
            - .:/var/www
        working_dir: /var/www
        ports:
            - "9000:9000"
        networks:
            - laravel_network
        depends_on:
            - mysql
        environment:
            - PHP_FPM_PORT=9000
            - COMPOSER_ALLOW_SUPERUSER=1

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: finance
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: finance
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - laravel_network

volumes:
    mysql_data:

networks:
    laravel_network:
        driver: bridge
