version: '3.8'

services:
  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    volumes:
      - ../gateway:/var/www/gateway
    ports:
      - "8000:80"

  finance:
    build:
      context: ../finance
      dockerfile: Dockerfile
    volumes:
      - ../finance:/var/www/finance
    ports:
      - "8001:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
